DROP TABLE IF EXISTS CATEGORY_TO_CATEGORY
GO

DROP TABLE IF EXISTS CATEGORIES
GO

CREATE TABLE CATEGORIES
	( 
		CATEGORY_URL VARCHAR(128) PRIMARY KEY WITH (IGNORE_DUP_KEY=ON),
		CATEGORY_TITLE VARCHAR(128),
		CATEGORY_CONTENT VARCHAR(MAX),
		CATEGORY_DOWNLOADED BIT NOT NULL DEFAULT 0
	) 

GO

DROP TABLE IF EXISTS ARTICLES
GO

CREATE TABLE ARTICLES
	(
		ARTICLE_URL VARCHAR(128) PRIMARY KEY WITH (IGNORE_DUP_KEY=ON),
		ARTICLE_TITLE VARCHAR(128),
		ARTICLE_CONTENT VARCHAR(MAX),
		ARTICLE_INFO VARCHAR(MAX),
		ARTICLE_DOWNLOADED BIT NOT NULL DEFAULT 0
	)

GO

CREATE TABLE CATEGORY_TO_CATEGORY
	(
		CATEGORY_URL_PARENT VARCHAR(128) FOREIGN KEY REFERENCES CATEGORIES(CATEGORY_URL),
		CATEGORY_URL_CHILD VARCHAR(128) FOREIGN KEY REFERENCES CATEGORIES(CATEGORY_URL),

		PRIMARY KEY (CATEGORY_URL_PARENT, CATEGORY_URL_CHILD)
	)

GO

DROP PROCEDURE IF EXISTS INSERT_CATEGORY_TO_DOWNLOAD

GO

CREATE PROCEDURE INSERT_CATEGORY_TO_DOWNLOAD
	@CATEGORY_URL VARCHAR(128)
AS
	IF NOT EXISTS(SELECT CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_URL=@CATEGORY_URL)
		INSERT INTO CATEGORIES (CATEGORY_URL) VALUES (@CATEGORY_URL)

GO

DROP PROCEDURE IF EXISTS GET_CATEGORY_TO_DOWNLOAD
GO

CREATE PROCEDURE GET_CATEGORY_TO_DOWNLOAD
	AS 
	SELECT TOP(1) CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_DOWNLOADED = 0

GO
DROP PROCEDURE IF EXISTS INSERT_CATEGORY
GO

CREATE PROCEDURE INSERT_CATEGORY
	@CATEGORY_URL VARCHAR(128),
	@CATEGORY_TITLE VARCHAR(128),
	@CATEGORY_CONTENT VARCHAR(MAX)
AS
	IF EXISTS(SELECT CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_URL = @CATEGORY_URL AND CATEGORY_DOWNLOADED = 0)
		UPDATE CATEGORIES SET CATEGORY_TITLE=@CATEGORY_TITLE, CATEGORY_CONTENT=@CATEGORY_CONTENT, CATEGORY_DOWNLOADED=1 WHERE CATEGORY_URL = @CATEGORY_URL
	ELSE IF NOT EXISTS(SELECT CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_URL = @CATEGORY_URL)
		INSERT INTO CATEGORIES (CATEGORY_URL, CATEGORY_TITLE, CATEGORY_CONTENT, CATEGORY_DOWNLOADED) VALUES (@CATEGORY_URL, @CATEGORY_TITLE, @CATEGORY_CONTENT, 1)

GO
DROP PROCEDURE IF EXISTS INSERT_ARTICLE_TO_DOWNLOAD
GO

CREATE PROCEDURE INSERT_ARTICLE_TO_DOWNLOAD
	@ARTICLE_URL VARCHAR(128)
AS
	IF NOT EXISTS(SELECT ARTICLE_URL FROM ARTICLES WHERE ARTICLE_URL = @ARTICLE_URL)
		INSERT INTO ARTICLES (ARTICLE_URL) VALUES (@ARTICLE_URL)

GO
DROP PROCEDURE IF EXISTS GET_ARTICLE_TO_DOWNLOAD
GO

CREATE PROCEDURE GET_ARTICLE_TO_DOWNLOAD
AS
	SELECT TOP(1) ARTICLE_URL FROM ARTICLES WHERE ARTICLE_DOWNLOADED = 0

GO
DROP PROCEDURE IF EXISTS INSERT_ARTICLE
GO

CREATE PROCEDURE INSERT_ARTICLE
	@ARTICLE_URL VARCHAR(128),
	@ARTICLE_TITLE VARCHAR(128),
	@ARTICLE_CONTENT VARCHAR(MAX),
	@ARTICLE_INFO VARCHAR(MAX)
AS
	IF EXISTS(SELECT ARTICLE_URL FROM ARTICLES WHERE ARTICLE_URL = @ARTICLE_URL AND ARTICLE_DOWNLOADED = 0)
		UPDATE ARTICLES SET ARTICLE_TITLE=@ARTICLE_TITLE, ARTICLE_CONTENT=@ARTICLE_CONTENT, ARTICLE_INFO=@ARTICLE_INFO, ARTICLE_DOWNLOADED=1 WHERE ARTICLE_URL = @ARTICLE_URL
	ELSE IF NOT EXISTS(SELECT ARTICLE_URL FROM ARTICLES WHERE ARTICLE_URL = @ARTICLE_URL)
		INSERT INTO ARTICLES (ARTICLE_URL, ARTICLE_TITLE, ARTICLE_CONTENT, ARTICLE_INFO, ARTICLE_DOWNLOADED) VALUES (@ARTICLE_URL, @ARTICLE_TITLE, @ARTICLE_CONTENT, @ARTICLE_INFO, 1)