DROP TABLE IF EXISTS CATEGORIES_RELATIONS
DROP TABLE IF EXISTS CATEGORIES
DROP TABLE IF EXISTS KEYWORDS_ARTICLES
DROP TABLE IF EXISTS ARTICLES
DROP TABLE IF EXISTS KEYWORDS
DROP TABLE IF EXISTS CATEGORIES_ARTICLES
GO

DROP PROCEDURE IF EXISTS GET_CATEGORIES_TO_DOWNLOAD
DROP PROCEDURE IF EXISTS GET_ARTICLES_TO_DOWNLOAD
DROP PROCEDURE IF EXISTS GET_KEYWORDS_TO_DOWNLOAD

DROP PROCEDURE IF EXISTS ADD_CATEGORY_TO_DOWNLOAD
DROP PROCEDURE IF EXISTS ADD_ARTICLE_TO_DOWNLOAD

DROP PROCEDURE IF EXISTS ADD_ARTICLE
DROP PROCEDURE IF EXISTS ADD_CATEGORY
DROP PROCEDURE IF EXISTS ADD_KEYWORD
DROP PROCEDURE IF EXISTS ADD_CATEGORY_RELATION
GO

CREATE TABLE CATEGORIES
	( 
		CATEGORY_URL VARCHAR(128) PRIMARY KEY WITH (IGNORE_DUP_KEY=ON),
		CATEGORY_TITLE NVARCHAR(128),
		CATEGORY_CONTENT NVARCHAR(MAX)
	) 

GO


CREATE TABLE ARTICLES
	(
		ARTICLE_URL VARCHAR(128) PRIMARY KEY WITH (IGNORE_DUP_KEY=ON),
		ARTICLE_TITLE NVARCHAR(128),
		ARTICLE_CONTENT NVARCHAR(MAX),
		ARTICLE_INFO NVARCHAR(MAX)
	)

GO

CREATE TABLE CATEGORIES_RELATIONS
	(
		CATEGORY_PARENT_URL VARCHAR(128) FOREIGN KEY REFERENCES CATEGORIES(CATEGORY_URL),
		CATEGORY_CHILD_URL VARCHAR(128) FOREIGN KEY REFERENCES CATEGORIES(CATEGORY_URL),

		PRIMARY KEY (CATEGORY_PARENT_URL, CATEGORY_CHILD_URL)
	)

GO

CREATE TABLE KEYWORDS
	(
		KEYWORD_URL VARCHAR(128) PRIMARY KEY,
		KEYWORD_TITLE NVARCHAR(128)
	)
	
CREATE TABLE KEYWORDS_ARTICLES
	(
		KEYWORD_URL VARCHAR(128) FOREIGN KEY REFERENCES KEYWORDS(KEYWORD_URL),
		ARTICLE_URL VARCHAR(128) FOREIGN KEY REFERENCES ARTICLES(ARTICLE_URL),
		KEYWORD_TEXT NVARCHAR(32),

		PRIMARY KEY (KEYWORD_URL, ARTICLE_URL)
	)

GO


CREATE PROCEDURE ADD_CATEGORY_TO_DOWNLOAD
	@CATEGORY_URL VARCHAR(128)
AS
	IF NOT EXISTS(SELECT CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_URL=@CATEGORY_URL)
		INSERT INTO CATEGORIES (CATEGORY_URL) VALUES (@CATEGORY_URL)

GO


CREATE PROCEDURE GET_CATEGORIES_TO_DOWNLOAD
	@COUNT INT
AS 
	SELECT TOP(@COUNT) CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_TITLE IS NULL
GO

DROP PROCEDURE IF EXISTS INSERT_CATEGORY
GO

CREATE PROCEDURE ADD_CATEGORY
	@CATEGORY_URL VARCHAR(128),
	@CATEGORY_TITLE NVARCHAR(128),
	@CATEGORY_CONTENT NVARCHAR(MAX)
AS
	IF EXISTS(SELECT CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_URL = @CATEGORY_URL AND CATEGORY_TITLE IS NULL)
		UPDATE CATEGORIES SET CATEGORY_TITLE=@CATEGORY_TITLE, CATEGORY_CONTENT=@CATEGORY_CONTENT WHERE CATEGORY_URL = @CATEGORY_URL
	ELSE IF NOT EXISTS(SELECT CATEGORY_URL FROM CATEGORIES WHERE CATEGORY_URL = @CATEGORY_URL)
		INSERT INTO CATEGORIES (CATEGORY_URL, CATEGORY_TITLE, CATEGORY_CONTENT) VALUES (@CATEGORY_URL, @CATEGORY_TITLE, @CATEGORY_CONTENT)

GO
DROP PROCEDURE IF EXISTS INSERT_ARTICLE_TO_DOWNLOAD
GO

CREATE PROCEDURE ADD_ARTICLE_TO_DOWNLOAD
	@ARTICLE_URL VARCHAR(128)
AS
	IF NOT EXISTS(SELECT ARTICLE_URL FROM ARTICLES WHERE ARTICLE_URL = @ARTICLE_URL)
		INSERT INTO ARTICLES (ARTICLE_URL) VALUES (@ARTICLE_URL)

GO

CREATE PROCEDURE GET_ARTICLES_TO_DOWNLOAD
	@COUNT INT
AS
	SELECT TOP(@COUNT) ARTICLE_URL FROM ARTICLES WHERE ARTICLE_TITLE IS NULL

GO

CREATE PROCEDURE ADD_ARTICLE
	@ARTICLE_URL VARCHAR(128),
	@ARTICLE_TITLE NVARCHAR(128),
	@ARTICLE_CONTENT NVARCHAR(MAX),
	@ARTICLE_INFO NVARCHAR(MAX)
AS
	IF EXISTS(SELECT ARTICLE_URL FROM ARTICLES WHERE ARTICLE_URL = @ARTICLE_URL AND ARTICLE_TITLE IS NULL)
		UPDATE ARTICLES SET ARTICLE_TITLE=@ARTICLE_TITLE, ARTICLE_CONTENT=@ARTICLE_CONTENT, ARTICLE_INFO=@ARTICLE_INFO WHERE ARTICLE_URL = @ARTICLE_URL
	ELSE IF NOT EXISTS(SELECT ARTICLE_URL FROM ARTICLES WHERE ARTICLE_URL = @ARTICLE_URL)
		INSERT INTO ARTICLES (ARTICLE_URL, ARTICLE_TITLE, ARTICLE_CONTENT, ARTICLE_INFO) VALUES (@ARTICLE_URL, @ARTICLE_TITLE, @ARTICLE_CONTENT, @ARTICLE_INFO)

GO

CREATE PROCEDURE ADD_KEYWORD
	@KEYWORD_URL VARCHAR(128),
	@ARTICLE_URL VARCHAR(128),
	@KEYWORD_TITLE NVARCHAR(128),
	@KEYWORD_TEXT NVARCHAR(32)
AS
	BEGIN
		IF EXISTS(SELECT KEYWORD_URL FROM KEYWORDS WHERE KEYWORD_URL = @KEYWORD_URL)
			UPDATE KEYWORDS SET KEYWORD_TITLE = @KEYWORD_TITLE WHERE KEYWORD_URL = @KEYWORD_URL
		ELSE
			INSERT INTO KEYWORDS (KEYWORD_URL, KEYWORD_TITLE) VALUES (@KEYWORD_URL, @KEYWORD_TITLE)
		IF NOT EXISTS(SELECT KEYWORD_URL FROM KEYWORDS WHERE KEYWORD_URL = @KEYWORD_URL)
			INSERT INTO KEYWORDS (KEYWORD_URL) VALUES (@KEYWORD_URL)
		IF NOT EXISTS(SELECT KEYWORD_URL, ARTICLE_URL FROM KEYWORDS_ARTICLES WHERE KEYWORD_URL = @KEYWORD_URL AND ARTICLE_URL = @ARTICLE_URL)
			INSERT INTO KEYWORDS_ARTICLES (KEYWORD_URL, ARTICLE_URL, KEYWORD_TEXT) VALUES (@KEYWORD_URL, @ARTICLE_URL, @KEYWORD_TEXT)
	END
GO

CREATE PROCEDURE ADD_CATEGORY_RELATION
	@CATEGORY_PARENT_URL VARCHAR(128),
	@CATEGORY_CHILD_URL VARCHAR(128)
AS
	IF NOT EXISTS(SELECT CATEGORY_PARENT_URL, CATEGORY_CHILD_URL FROM CATEGORIES_RELATIONS WHERE CATEGORY_PARENT_URL = @CATEGORY_PARENT_URL AND CATEGORY_CHILD_URL = @CATEGORY_CHILD_URL)
		INSERT INTO CATEGORIES_RELATIONS (CATEGORY_PARENT_URL, CATEGORY_CHILD_URL) VALUES (@CATEGORY_PARENT_URL, @CATEGORY_CHILD_URL)
GO

CREATE PROCEDURE GET_KEYWORDS_TO_DOWNLOAD
	@COUNT INT
AS
	SELECT TOP(@COUNT) KEYWORD_URL FROM KEYWORDS WHERE KEYWORD_TITLE IS NULL

CREATE PROCEDURE DELETE_CATEGORY
	@CATEGORY_URL VARCHAR(128)
AS
	BEGIN
		delete from CATEGORIES_RELATIONS WHERE CATEGORY_PARENT_URL = @CATEGORY_URL OR CATEGORY_CHILD_URL = @CATEGORY_URL
		DELETE FROM CATEGORIES WHERE CATEGORY_URL = @CATEGORY_URL
	END